---
- name: Yum check-update
  ansible.builtin.command: yum check-update # noqa command-instead-of-module
  register: yum_check_update
  changed_when: "yum_check_update.rc != 0"
- name: Run yum update -y
  ansible.builtin.command: yum update -y # noqa command-instead-of-module
  register: yum_update
  changed_when: "yum_update.rc == 0"
  when: "yum_check_update.rc != 0"
