---
- name: Execute jls
  ansible.builtin.shell: |
    set -o errexit
    set -o pipefail
    set -o nounset

    jls | sed 1d | awk '{ print $3 }'
  register: cmd_jail_id_list
  changed_when: false
- name: Set freebsd_running_jails
  ansible.builtin.set_fact:
    freebsd_running_jails: "{{ cmd_jail_id_list.stdout_lines }}"
