- name: set my_pkg_cmd var for host
  set_fact:
    my_pkg_cmd: pkg
  when:
    - jail_id == 0
- name: set my_pkg_cmd for jail
  set_fact:
    my_pkg_cmd: 'pkg -j {{ jail_id }}'
  when:
    - jail_id != 0
- name: pkg update 
  command: '{{ my_pkg_cmd }} update'
  register: pkg_update_y
  changed_when: "pkg_update_y.rc != 0"
- name: verify if there are upgrades available
  command: '{{ my_pkg_cmd }} upgrade -n'
  register: pkg_upgrade_n
  changed_when: "pkg_upgrade_n.rc != 0"
  failed_when: "pkg_upgrade_n.rc > 1"
- name: upgrade
  command: '{{ my_pkg_cmd }} upgrade -y'
  when: "pkg_upgrade_n.rc != 0"
